container_task:
  container:
    dockerfile: Dockerfile
  only_if: $CIRRUS_BRANCH == 'master'
  env:
    DOCKER_USERNAME: ENCRYPTED[...]
    DOCKER_PASSWORD: ENCRYPTED[...]
  script:
  - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
  - release.xsh
