name: Cirrus Poker
description: Pokes Cirrus to make a new build
inputs:
  CIRRUS_TOKEN:
    description: Cirrus authentication token
    required: true
  branch:
    description: Branch to build
    required: true
    default: master
  # task:
  #   description: Task to trigger
  #   required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
